ALTER TYPE "MlmLevel" ADD VALUE IF NOT EXISTS 'CUSTOMER';

ALTER TABLE "User"
ALTER COLUMN "mlmLevel" SET DEFAULT 'CUSTOMER';

UPDATE "User"
SET "mlmLevel" = 'CUSTOMER'
WHERE "role" IN ('CUSTOMER', 'DELIVERY_AGENT', 'ADMIN')
  AND "mlmLevel" = 'AYIZAN';
