ALTER TABLE "PosSale"
ADD COLUMN "deliveryRequested" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "deliveryFee" DECIMAL(10,2) NOT NULL DEFAULT 0,
ADD COLUMN "totalWeightLbs" DECIMAL(10,2) NOT NULL DEFAULT 0;
